---
# Интервал появления сундука в минутах
interval: 1

# Сообщение о появлении сундука
# {x}
# {y}
# {z}
message: §r§a> §fНа точку §a{x}§f, §a{y}§f, §a{z} §fбыл сброшен груз! Успей забрать!

# Радиус появления сундука
drop_x_min: 0
drop_x_max: 10
drop_z_min: 0
drop_z_max: 10

# Радиус спавна, куда сундук падать не будет
spawn_x_min: 2
spawn_x_max: 8
spawn_z_min: 2
spawn_z_max: 8

# Предметы и шанс их выпадения
# "id:meta": chance
items:
  "1": 100
  "1:1": 90
  "1:2": 80
  "1:3": 70
  "1:4": 60
  "1:5": 50
  "1:6": 40
...
